### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by princemaple** [garyf/jwt_claims_ex#6]
Hi @garyf ,

Not sure if you have seen my email.
Could you let me help you with maintaining your two awesome elixir jwt packages please?
Yours are my favorite jwt packages. (The others are joken and guardian)
I really want to keep them going.

Thanks a lot for building them!

Regards,
Po

**Comment by sarat1669** [comment]
@princemaple , I too love this project, but I think it is feature complete. What else do you want to implement?

**Comment by princemaple** [comment]
Simply want to keep it up to date and merge good PRs.

**Comment by princemaple** [comment]
@garyf FYI you haven't released 0.0.5 yet.
